# Generated by Django 5.0.7 on 2024-07-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_environmentalinitiative_usercontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalinitiative',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.company'),
        ),
    ]
