# Generated by Django 5.0.7 on 2024-07-23 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_faq_delete_companyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eco_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_eco_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EcoSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('energy_efficiency', models.IntegerField(default=0)),
                ('waste_management', models.IntegerField(default=0)),
                ('sustainable_sourcing', models.IntegerField(default=0)),
                ('water_conservation', models.IntegerField(default=0)),
                ('employee_training', models.IntegerField(default=0)),
                ('green_certifications', models.IntegerField(default=0)),
                ('carbon_footprint', models.IntegerField(default=0)),
                ('renewable_energy', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.company')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
