# Generated by Django 5.0.7 on 2024-07-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(to='myApp.company',on_delete=django.db.models.deletion.CASCADE),
        ),
    ]
