# Generated by Django 5.0.7 on 2024-07-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_environmentalinitiative_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalinitiative',
            old_name='organization',
            new_name='company',
        ),
    ]
