# Generated by Django 5.0.7 on 2024-07-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_organization_environmentalinitiative_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalinitiative',
            old_name='company',
            new_name='organization',
        ),
    ]
