# Generated by Django 5.0.7 on 2024-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_company_environmentalinitiative_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalinitiative',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
