# Generated by Django 5.0.7 on 2024-07-21 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_environmentalinitiative_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalinitiative',
            name='organization',
        ),
        migrations.AddField(
            model_name='environmentalinitiative',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company'),
        ),
    ]
