# Generated by Django 5.0.7 on 2024-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_environmentalinitiative_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
